---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: ing-e2e-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: ing-e2e-broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  postgres:
    image: postgres:15.2-alpine
    container_name: ing-e2e-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: 'ing_user'
      POSTGRES_PASSWORD: 'ing_pass'
      POSTGRES_DB: 'ing'

  redis1:
    image: redis:7.0.9
    container_name: ing-e2e-redis1
    ports:
      - "6379:6379"
    volumes:
      - ./scripts/redis.conf:/etc/redis/redis.conf
      - ./scripts/redis.acl:/etc/redis/redis.acl
    command: ["redis-server", "/etc/redis/redis.conf"]

  redis2:
    image: redis:7.0.9
    container_name: ing-e2e-redis2
    ports:
      - "6380:6379"
    volumes:
      - ./scripts/redis.conf:/etc/redis/redis.conf
      - ./scripts/redis.acl:/etc/redis/redis.acl
    command: ["redis-server", "/etc/redis/redis.conf"]

  redis3:
    image: redis:7.0.9
    container_name: ing-e2e-redis3
    ports:
      - "6381:6379"
    volumes:
      - ./scripts/redis.conf:/etc/redis/redis.conf
      - ./scripts/redis.acl:/etc/redis/redis.acl
    command: ["redis-server", "/etc/redis/redis.conf"]
