---
version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: ing-e2e-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: ing-e2e-broker
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  postgres:
    image: postgres:15.2-alpine
    container_name: ing-e2e-postgres
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: 'ing_user'
      POSTGRES_PASSWORD: 'ing_pass'
      POSTGRES_DB: 'ing'

  redis1:
    image: redis:7.0.9
    container_name: ing-e2e-redis1
    volumes:
      - ./scripts/redis.conf:/etc/redis/redis.conf
      - ./scripts/redis.acl:/etc/redis/redis.acl
    command: ["redis-server", "/etc/redis/redis.conf"]

  redis2:
    image: redis:7.0.9
    container_name: ing-e2e-redis2
    volumes:
      - ./scripts/redis.conf:/etc/redis/redis.conf
      - ./scripts/redis.acl:/etc/redis/redis.acl
    command: ["redis-server", "/etc/redis/redis.conf"]

  redis3:
    image: redis:7.0.9
    container_name: ing-e2e-redis3
    volumes:
      - ./scripts/redis.conf:/etc/redis/redis.conf
      - ./scripts/redis.acl:/etc/redis/redis.acl
    command: ["redis-server", "/etc/redis/redis.conf"]

  app:
    image: oizgagin/ing-dev:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on: [ "broker", "postgres", "redis1", "redis2", "redis3" ]
    container_name: ing-dev-app
    ports:
      - "8080:8080"
      - "8081:8081"
