FROM golang:1.20-alpine as build

ADD . /build
WORKDIR /build

RUN \
    cd cmd && go build -o /build/ing && \
    cd /build && \
    cp ./scripts/wait-for-it/wait-for-it.sh /build/wait-for-it.sh && \
    cp ./scripts/entrypoint.dev.sh /build/entrypoint.dev.sh && \
    cp ./scripts/config.dev.toml /build/config.toml


FROM alpine:3.17

RUN apk add --no-cache bash

COPY --from=build /build/ing /usr/local/bin/ing
COPY --from=build /build/config.toml /usr/local/etc/ing/config.toml
COPY --from=build /build/wait-for-it.sh /usr/local/bin/wait-for-it.sh
COPY --from=build /build/entrypoint.dev.sh /usr/local/bin/entrypoint.dev.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.dev.sh"]
